require('../');
console.log("---------------------------------");
console.log("hello %s", "world", " Welcome!");
console.info("%s %s %d", "Hello", "Year", 2024);
console.warn('%s %s %d %o', 'foo', 'bar', 1, { y: 'v' });
console.error("worker pid %d", process.pid);
console.log("");
console.log("--------------------------------");
//highlightMode: 'type-message',//type|line|message|type-message
console.set('highlightMode', 'line');
console.log("hello %s", "world", " Welcome!");
console.info("%s %s %d", "Hello", "Year", 2024);
console.warn('%s %s %d %o', 'foo', 'bar', 1, { y: 'v' });
console.error("worker pid %d", process.pid);
console.log("");
console.log("--------------------------------");
console.set('showType', true);
console.log("hello %s", "world", " Welcome!");
console.info("%s %s %d", "Hello", "Year", 2024);
console.warn('%s %s %d %o', 'foo', 'bar', 1, { y: 'v' });
console.error("worker pid %d", process.pid);
console.log("");
console.log("--------------------------------");
console.set('stackIndention', 35);
console.log("hello %s", "world", " Welcome!");
console.info("%s %s %d", "Hello", "Year", 2024);
console.warn('%s %s %d %o', 'foo', 'bar', 1, { y: 'v' });
console.error("worker pid %d", process.pid);
console.log("");
console.log("---------------------------------");
console.set('stackIndention', 55);
console.log("hello %s", "world", " Welcome!");
console.info("%s %s %d", "Hello", "Year", 2024);
console.warn('%s %s %d %o', 'foo', 'bar', 1, { y: 'v' });
console.error("worker pid %d", process.pid);
console.log("");
console.log("---------------------------------");
console.set('highlightMode', 'type');
console.log("hello %s", "world", " Welcome!");
console.info("%s %s %d", "Hello", "Year", 2024);
console.warn('%s %s %d %o', 'foo', 'bar', 1, { y: 'v' });
console.error("worker pid %d", process.pid);
console.log("");
console.log("---------------------------------");
console.set('showSource', false);
console.log("hello %s", "world", " Welcome!");
console.info("%s %s %d", "Hello", "Year", 2024);
console.warn('%s %s %d %o', 'foo', 'bar', 1, { y: 'v' });
console.error("worker pid %d", process.pid);