

// 0.21 ms per console.log for highlightMode: 'type-message'
// 0.21 ms per console.log for highlightMode: 'message'

console.info("******");
console.info("trace-o-matic is ENABLED");
console.info("For more info:https://github.com/restimguay/trace-o-matic");
console.info("******");
console.info("You'll now experience the console message generated by trace-o-matic");
console.info("This information will not call any of your custom API");

require('./src/TraceOMatic');
